name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm install puppeteer
      - run: sudo apt-get install -y libgbm-dev
      - run: sudo apt-get install -y fonts-ipafont-gothic
      - run: sudo apt-get install -y gconf-service libasound2 libatk1.0-0 libcups2 libdbus-1-3 libxcomposite1 libxdamage1 libxrandr2 libgbm1 libgtk-3-0 libnss3 libxss1 libxtst6 xdg-utils
      - run: mkdir -p /home/runner/work/SeatChanger/SeatChanger/public/images
      - run: DEBUG=puppeteer:* npm test
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'false'
        PUPPETEER_EXECUTABLE_PATH: '/usr/bin/chromium-browser'
        NODE_ENV: 'test'
        PUPPETEER_ARGS: '--no-sandbox --disable-setuid-sandbox --disable-dev-shm-usage'
